FROM alpine

RUN apk add --update nodejs && apk add --update npm

WORKDIR /app

COPY package.json .
RUN npm i
COPY . .

CMD ["npm","run","start"]

# docker run -e CHOKIDAR_USEPOLLING=true -it -p 3000:3000 -v ${pwd}:/app anandavj/reactprojectdev